import esbuild from 'esbuild';
import { copyFile, mkdir } from 'node:fs/promises';
import { builtinModules } from 'node:module';
import process from 'node:process';

const production = process.argv[2] === 'production';
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: https://github.com/Joaquim-Frances/obsidian-notelert-plugin
*/
`;

await mkdir('dist', { recursive: true });

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: production ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
  minify: production,
});

await copyFile('manifest.json', 'dist/manifest.json');

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
